/* Generated By:JJTree: Do not edit this line. ASTBreakpoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTBreakpoint extends SimpleNode
{
  public ASTBreakpoint(int id)
  {
    super(id);
  }

  public ASTBreakpoint(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public int line;
  public int instructionIndex;
}
/*
 * JavaCC - OriginalChecksum=14453513de7cd61e9ff11c29cdddd4c9 (do not edit this line)
 */
