/* Generated By:JJTree: Do not edit this line. ASTComma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTComma extends PrintSubExpressionNode
{
  public ASTComma(int id)
  {
    super(id);
  }

  public ASTComma(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=5c445b72111012204d1e7aabfca5ee04 (do not edit this
 * line)
 */
