/* Generated By:JJTree: Do not edit this line. ASTCsr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*EDITED*/

package com.fx702p.parser;

public class ASTCsr extends PrintSubExpressionNode
{
  public ASTCsr(int id)
  {
    super(id);
  }

  public ASTCsr(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=538f1ae9824e38fe02d63825e81dacda (do not edit this
 * line)
 */
