/* Generated By:JJTree: Do not edit this line. ASTFloat.java */
/*EDITED*/

package com.fx702p.parser;

import java.math.BigDecimal;

public class ASTFloat extends EscapedCharNode
{
  public ASTFloat(int id)
  {
    super(id);
  }

  public ASTFloat(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public BigDecimal value;
  public String image;
}
