/* Generated By:JJTree: Do not edit this line. ASTGreaterOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTGreaterOrEqual extends EscapedCharNode
{
  public ASTGreaterOrEqual(int id)
  {
    super(id);
  }

  public ASTGreaterOrEqual(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=a5973eaf6cfda4ca4ac9ddbb0d00843d (do not edit this
 * line)
 */
