/* Generated By:JJTree: Do not edit this line. ASTInteger.java */
/*EDITED*/

package com.fx702p.parser;

import java.math.BigDecimal;

public class ASTInteger extends SimpleNode
{
  public ASTInteger(int id)
  {
    super(id);
  }

  public ASTInteger(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public BigDecimal value;
  public String image;
}
