/* Generated By:JJTree: Do not edit this line. ASTInputVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

import com.fx702p.emulator.InstructionBoundary;

public class ASTInputVariable extends SimpleNode
{
  public ASTInputVariable(int id)
  {
    super(id);
  }

  public ASTInputVariable(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public int getLineIndexInSourceCode()
  {
    return ((ASTInput)parent).getLineIndexInSourceCode();
  }

  public InstructionBoundary getSubInstructionBoundary()
  {
    return ((ASTInput)parent).getSubInstructionBoundary(this);
  }
}
/*
 * JavaCC - OriginalChecksum=48966354c1a0ee39b05fa6411fb0144d (do not edit this
 * line)
 */
