/* Generated By:JJTree: Do not edit this line. ASTLesserOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTLesserOrEqual extends EscapedCharNode
{
  public ASTLesserOrEqual(int id)
  {
    super(id);
  }

  public ASTLesserOrEqual(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=10dbaceb0bd4daf9ebb31337aff18b49 (do not edit this
 * line)
 */
