/* Generated By:JJTree: Do not edit this line. ASTMultiplePrograms.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTMultiplePrograms extends SimpleNode
{
  public ASTMultiplePrograms(int id)
  {
    super(id);
  }

  public ASTMultiplePrograms(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public int getBeginLine()
  {
    return beginLine;
  }

  public void setBeginLine(int aBeginLine)
  {
    beginLine = aBeginLine;
  }

  public int getEndLine()
  {
    return endLine;
  }

  public void setEndLine(int anEndLine)
  {
    endLine = anEndLine;
  }

  protected int beginLine = -1;
  protected int endLine = -1;
}
/* JavaCC - OriginalChecksum=563254ed27352170c953ed472ed99d28 (do not edit this line) */
