/* Generated By:JJTree: Do not edit this line. ASTNotEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTNotEqual extends EscapedCharNode
{
  public ASTNotEqual(int id)
  {
    super(id);
  }

  public ASTNotEqual(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=00da043535379e52e704c5e73e616c7b (do not edit this
 * line)
 */
