/* Generated By:JJTree: Do not edit this line. ASTProgramSignature.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTProgramSignature extends SimpleNode
{
  public ASTProgramSignature(int id)
  {
    super(id);
  }

  public ASTProgramSignature(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public String signature;
  public int beginLine;
  public int endLine;
}
/*
 * JavaCC - OriginalChecksum=97214d74895fd7549aff56dd4fe0c54b (do not edit this
 * line)
 */
