/* Generated By:JJTree: Do not edit this line. ASTPrintFormat.java */
/*EDITED*/

package com.fx702p.parser;


public class ASTPrintFormat extends PrintSubExpressionNode
{
  public ASTPrintFormat(int id)
  {
    super(id);
  }

  public ASTPrintFormat(Fx702pParser p, int id)
  {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public String format;
}
