/* Generated By:JJTree: Do not edit this line. ASTPrtExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

/*EDITED*/

package com.fx702p.parser;

public class ASTPrtExpression extends PrintSubExpressionNode
{
  public ASTPrtExpression(int id)
  {
    super(id);
  }

  public ASTPrtExpression(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=b9501a4ba4dc6368ac2eb8ae5c04f277 (do not edit this
 * line)
 */
