/* Generated By:JJTree: Do not edit this line. ASTString.java */
/*EDITED*/

package com.fx702p.parser;


public class ASTString extends EscapedCharNode
{
  public ASTString(int id)
  {
    super(id);
  }

  public ASTString(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public String value;
  public String image;
}
