/* Generated By:JJTree: Do not edit this line. ASTSingleProgram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTSingleProgram extends SimpleNode
{
  public ASTSingleProgram(int id)
  {
    super(id);
  }

  public ASTSingleProgram(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }

  public int getProgramNumber()
  {
    return programNumber;
  }

  public void setProgramNumber(int aProgramNumber)
  {
    programNumber = aProgramNumber;
  }

  public String getPassword()
  {
    return password;
  }

  public void setPassword(String aPassword)
  {
    password = aPassword;
  }

  public int getBeginLine()
  {
    return beginLine;
  }

  public void setBeginLine(int aBeginLine)
  {
    beginLine = aBeginLine;
  }

  public int getEndLine()
  {
    return endLine;
  }

  public void setEndLine(int anEndLine)
  {
    endLine = anEndLine;
  }

  protected int programNumber;
  protected String password;
  protected int beginLine = -1;
  protected int endLine = -1;
}
/* JavaCC - OriginalChecksum=b621f5f87aa271551b57c669983db2fe (do not edit this line) */
