/* Generated By:JJTree: Do not edit this line. ASTSemicolon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/*EDITED*/

package com.fx702p.parser;

public class ASTSemicolon extends PrintSubExpressionNode
{
  public ASTSemicolon(int id)
  {
    super(id);
  }

  public ASTSemicolon(Fx702pParser p, int id)
  {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(Fx702pParserVisitor visitor, Object data)
  {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=ecbdaf7c38f3a66be9668b4dfb55c4ba (do not edit this
 * line)
 */
