package com.fx702p.emulator;

import java.util.*;

public class Characters
{
  static public boolean isDisplayable(char c)
  {
    return drawingsByChar.containsKey(c);
  }

  static public boolean isValidStringCharacter(char c)
  {
    return c != '\'' && c != '"' && c != '_' && isDisplayable(c);
  }

  static public String[] getCharacterDrawings(char c)
  {
    String[] drawings = drawingsByChar.get(c);
    if (drawings == null)
    {
      Console.reportError("Cannot find drawings for character " + c + ", value=" + (int)c);
      return drawingsByChar.get('?');
    }
    return drawings;
  }


  static private Map<Character, String[]> drawingsByChar = new Hashtable<Character, String[]>();

  // Some ascii characters are used to represent the Fx702p special ones
  // ^ for up-arrow/power function
  // e for the small-uppercase E or exponent in numbers
  // p for Pi
  // { for <=
  // } for >=
  // ~ for the "different" sign, /=
  static public final String CHARACTERS_ORDER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 .e+-*/,;:!?()<>=\"#$^p{}~_'\"o";

  static public final String CHARACTERS[][] =
    {
        {
          " XXX ",
          "X   X",
          "X   X",
          "XXXXX",
          "X   X",
          "X   X",
          "X   X",
        },
        {
          "XXXX ",
          "X   X",
          "X   X",
          "XXXX ",
          "X   X",
          "X   X",
          "XXXX ",
        },
        {
          " XXX ",
          "X   X",
          "X    ",
          "X    ",
          "X    ",
          "X   X",
          " XXX ",
        },
        {
          "XXX  ",
          "X  X ",
          "X   X",
          "X   X",
          "X   X",
          "X  X ",
          "XXX  ",
        },
        {
          "XXXXX",
          "X    ",
          "X    ",
          "XXXX ",
          "X    ",
          "X    ",
          "XXXXX",
        },
        {
          "XXXXX",
          "X    ",
          "X    ",
          "XXXX ",
          "X    ",
          "X    ",
          "X    ",
        },
        {
          " XXX ",
          "X   X",
          "X    ",
          "X XXX",
          "X   X",
          "X   X",
          " XXXX",
        },
        {
          "X   X",
          "X   X",
          "X   X",
          "XXXXX",
          "X   X",
          "X   X",
          "X   X",
        },
        {
          " XXX ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          " XXX ",
        },
        {
          "  XXX",
          "   X ",
          "   X ",
          "   X ",
          "   X ",
          "X  X ",
          " XX  ",
        },
        {
          "X   X",
          "X  X ",
          "X X  ",
          "XX   ",
          "X X  ",
          "X  X ",
          "X   X",
        },
        {
          "X    ",
          "X    ",
          "X    ",
          "X    ",
          "X    ",
          "X    ",
          "XXXXX",
        },
        {
          "X   X",
          "XX XX",
          "X X X",
          "X X X",
          "X   X",
          "X   X",
          "X   X",
        },
        {
          "X   X",
          "X   X",
          "XX  X",
          "X X X",
          "X  XX",
          "X   X",
          "X   X",
        },
        {
          " XXX ",
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          " XXX ",
        },
        {
          "XXXX ",
          "X   X",
          "X   X",
          "XXXX ",
          "X    ",
          "X    ",
          "X    ",
        },
        {
          " XXX ",
          "X   X",
          "X   X",
          "X   X",
          "X X X",
          "X  X ",
          " XX X",
        },
        {
          "XXXX ",
          "X   X",
          "X   X",
          "XXXX ",
          "X X  ",
          "X  X ",
          "X   X",
        },
        {
          " XXX ",
          "X   X",
          "X    ",
          " XXX ",
          "    X",
          "X   X",
          " XXX ",
        },
        {
          "XXXXX",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
        },
        {
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          " XXX ",
        },
        {
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          "X   X",
          " X X ",
          "  X  ",
        },
        {
          "X   X",
          "X   X",
          "X   X",
          "X X X",
          "X X X",
          "XX XX",
          "X   X",
        },
        {
          "X   X",
          "X   X",
          " X X ",
          "  X  ",
          " X X ",
          "X   X",
          "X   X",
        },
        {
          "X   X",
          "X   X",
          " X X ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
        },
        {
          "XXXXX",
          "    X",
          "   X ",
          "  X  ",
          " X   ",
          "X    ",
          "XXXXX",
        },
        {
          " XXX ",
          "X   X",
          "X  XX",
          "X X X",
          "XX  X",
          "X   X",
          " XXX ",
        },
        {
          "  X  ",
          " XX  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          " XXX ",
        },
        {
          " XXX ",
          "X   X",
          "    X",
          "   X ",
          "  X  ",
          " X   ",
          "XXXXX",
        },
        {
          "XXXXX",
          "   X ",
          "  X  ",
          "   X ",
          "    X",
          "X   X",
          " XXX ",
        },
        {
          "   X ",
          "  XX ",
          " X X ",
          "X  X ",
          "XXXXX",
          "   X ",
          "   X ",
        },
        {
          "XXXXX",
          "X    ",
          "XXXX ",
          "    X",
          "    X",
          "X   X",
          " XXX ",
        },
        {
          "  XX ",
          " X   ",
          "X    ",
          "XXXX ",
          "X   X",
          "X   X",
          " XXX ",
        },
        {
          "XXXXX",
          "    X",
          "   X ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
        },
        {
          " XXX ",
          "X   X",
          "X   X",
          " XXX ",
          "X   X",
          "X   X",
          " XXX ",
        },
        {
          " XXX ",
          "X   X",
          "X   X",
          " XXXX",
          "    X",
          "   X ",
          " XX  ",
        },
        {
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
        },
        {
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
          " XX  ",
          " XX  ",
        },
        {
          "     ",
          "     ",
          "XXXXX",
          "X    ",
          "XXXX ",
          "X    ",
          "XXXXX",
        },
        {
          "     ",
          "  X  ",
          "  X  ",
          "XXXXX",
          "  X  ",
          "  X  ",
          "     ",
        },
        {
          "     ",
          "     ",
          "     ",
          "XXXXX",
          "     ",
          "     ",
          "     ",
        },
        {
          "     ",
          "  X  ",
          "X X X",
          " XXX ",
          "X X X",
          "  X  ",
          "     ",
        },
        {
          "     ",
          "    X",
          "   X ",
          "  X  ",
          " X   ",
          "X    ",
          "     ",
        },
        {
          "     ",
          "     ",
          "     ",
          "     ",
          " XX  ",
          "  X  ",
          " X   ",
        },
        {
          "     ",
          " XX  ",
          " XX  ",
          "     ",
          " XX  ",
          "  X  ",
          " X   ",
        },
        {
          "     ",
          " XX  ",
          " XX  ",
          "     ",
          " XX  ",
          " XX  ",
          "     ",
        },
        {
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
          "     ",
          "  X  ",
        },
        {
          " XXX ",
          "X   X",
          "    X",
          "   X ",
          "  X  ",
          "     ",
          "  X  ",
        },
        {
          "  X  ",
          " X   ",
          "X    ",
          "X    ",
          "X    ",
          " X   ",
          "  X  ",
        },
        {
          " X   ",
          "  X  ",
          "   X ",
          "   X ",
          "   X ",
          "  X  ",
          " X   ",
        },
        {
          "   X ",
          "  X  ",
          " X   ",
          "X    ",
          " X   ",
          "  X  ",
          "   X ",
        },
        {
          "X    ",
          " X   ",
          "  X  ",
          "   X ",
          "  X  ",
          " X   ",
          "X    ",
        },
        {
          "     ",
          "     ",
          "XXXXX",
          "     ",
          "XXXXX",
          "     ",
          "     ",
        },
        {
          "XX XX",
          " X  X",
          "X  X ",
          "     ",
          "     ",
          "     ",
          "     ",
        },
        {
          " X X ",
          " X X ",
          "XXXXX",
          " X X ",
          "XXXXX",
          " X X ",
          " X X ",
        },
        {
          "  X  ",
          " XXXX",
          "X X  ",
          " XXX ",
          "  X X",
          "XXXX ",
          "  X  ",
        },
        {
          "  X  ",
          " XXX ",
          "X X X",
          "  X  ",
          "  X  ",
          "  X  ",
          "  X  ",
        },
        {
          "     ",
          "     ",
          "XXXXX",
          " X X ",
          " X X ",
          " X X ",
          "X  XX",
        },
        {
          "     ",
          "   X ",
          "  X  ",
          " X   ",
          "XXXXX",
          "     ",
          "XXXXX",
        },
        {
          "     ",
          " X   ",
          "  X  ",
          "   X ",
          "XXXXX",
          "     ",
          "XXXXX",
        },
        {
          "     ",
          " X   ",
          "XXXXX",
          "  X  ",
          "XXXXX",
          "   X ",
          "     ",
        },
        {
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
          "     ",
          "XXXXX",
        },
        {
          " XX  ",
          "  X  ",
          " X   ",
          "     ",
          "     ",
          "     ",
          "     ",
        },
        {
          "XX XX",
          " X  X",
          "X  X ",
          "     ",
          "     ",
          "     ",
          "     ",
        },
        {
          " XX  ",
          "X  X ",
          "X  X ",
          " XX  ",
          "     ",
          "     ",
          "     ",
        },
    };

  static
  {
    for (int i = 0, last = CHARACTERS_ORDER.length(); i < last; i++)
    {
      drawingsByChar.put(CHARACTERS_ORDER.charAt(i), CHARACTERS[i]);
    }
  }

  static public final char CURSOR_CHAR = '_';

  static public final int WIDTH = 5;
  static public final int HEIGHT = 7;
}
